### PR TITLE
sidebar responsive on mobile #1

### PR DESCRIPTION
**Pull request by s-babaeizadeh**
Hello,

I hope you had a great day during your holiday!

I have completed the task of making the sidebar responsive for mobile devices. I would greatly appreciate it if you could review my changes, and if everything looks good, please merge them into the main branch.

Key Changes:
Optimized the sidebar content and navigation for better readability on mobile devices.
Ensured consistent styling and responsiveness across different screen sizes.

The sidebar behaves as expected and provides a seamless user experience on mobile, tablet, and desktop devices.

Thank you for your time!

Best regards,
Soudeh Babaeizadeh

### CODE REVIEW

**Comment by Oslonline** [comment]
Hello Soudeh,

Thank you once again for your valuable contribution to this project! Here’s a quick summary of some small and straightforward changes that you could make before I merge this PR. If you’re unable to or prefer not to, just let me know, and I can handle these myself:

- Add your .history folder to your local .gitignore to exclude it from this and future PRs.
- Make the sidebar fixed on mobile to prevent scrolling/white space at the bottom if the page height exceeds that of the sidebar.
- Ensure all icons, including the logo, are centered. You can remove any unnecessary margin/padding on mobile for better alignment.
- For improved UI/UX, consider redirecting users to the homepage of a category (e.g., Generators) when they click on a menu item, which will enhance the visibility of the different tools.

Thank you for your time and effort in helping to improve this toolbox and for contributing to open source. I appreciate your support in making the first contribution experience a positive one !

**Comment by Oslonline** [comment]
PS : make sure to sync changes between your fork and the main branch ;)

**Comment by s-babaeizadeh** [comment]
Hello, thank you for reviewing and commenting on the last version.

The .history folder has been added to .gitignore, and the icons are centered.
The sidebar has been fixed on mobile to prevent scrolling.
I am happy to work on the last comment, but I believe it can be a separate issue on its own. Would you mind creating a new issue to handle this UI/UX concern?

**Comment by Oslonline** [comment]
Hi, sorry again for the delay, iv'e made some minor changes on your changes feel free to look a it before working on other things.
For the last needed changes i can open a new issue for sure and assign it to you.

Thanks again for your contribution !

**Pull request merged**
